### ISSUE TITLE
collect and persist basic text data

### ISSUE THREAD

**Issue by disperate** [grafit-io/grafit#1]
**Description of problem**
To build a concept extraction algorithm, we need some text data. The data should be in a script readable format.

**Solution**
A table/file with ten to twenty articles.
Every article should contains 200 to 1000 words.

**Additional context**
- [x] What language should be supported? 
- [x] Where should the data be stored? Database?

**Criteria for acceptance**
- [x] define the supported language
- [x] define data structure
- [x] collect data - [Don't Be Cute with Your Test Data](https://github.com/97-things/97-things-every-programmer-should-know/blob/4e03ea6022379dc32f4b0cce82b64c323d7f23c1/en/thing_25/README.md)

**Comment by disperate** [comment]
I suggest we start by supporting the English language only. The existing solution works with an English corpus as well so there is less risk associated with this approach.
But we should keep an eye on expandability too be able to build multi language support further down the line.

For the data-storage I suggest we use a PostgreSQL database as we need some kind of database anyway. 

@code-inflation any thoughts?

**Comment by code-inflation** [comment]
I agree with you that starting with English language support only would be a good idea. We can always add support for other languages later on.

Using PostgreSQL as a database is fine by me. 👍
