### ISSUE TITLE
setup knowledge graph runner

### ISSUE THREAD

**Issue by code-inflation** [grafit-io/grafit#10]
**Description of problem**
The application needs to be able to generate a graph from text data.

**Solution**
The knowledge graph runner should be the link between the text data #1 and the keyphrase extractor #9. 
A graph has to be created that combines the generated concept nodes and text/ content nodes. The nodes should be automatically linked to the corresponding concepts

**Additional context**
![systemubersicht sprint 1](https://user-images.githubusercontent.com/1553087/47072706-dfb2d800-d1f6-11e8-87ff-865a4c0ae20b.png)

**Criteria for acceptance**
- [x] The knowledge graph runner uses the keyphrase extractor #9 and applies it on the text data #1 
- [x] Using the auto generated keyphrases a graph is created that connects content nodes with their concepts
- [x] The graph is made available for the REST API (stored in a graph database)

**Comment by code-inflation** [comment]
The knowledge graph runner is complete. However the graph is not yet stored in a graph database. The integration of a graph DB was moved to sprint 2, see issue #16
