### ISSUE TITLE
Login Form

### ISSUE THREAD

**Issue by disperate** [grafit-io/grafit#14]
**Description of problem**
Currently the API Endpoint for user authentication is available. There is an Endpoint at `/api-token-auth` where you can redeem a Token by providing a valid username and password. 
The token is necessary to authenticate any further requests on the API.

As a user i want to login to authenticate myself on the service once.

**Solution**
Provide a login form where the user can authenticate himself. Store the token for a reasonable time frame to prevent the user from having to login again. If the token is not availbale, redirect the user to the login form.

**Additional context**
![image](https://user-images.githubusercontent.com/9363716/47781561-43acc480-dcfe-11e8-815c-f067dc45c9d2.png)

**Criteria for acceptance**
- [x] There is a login form.
- [x] Login data is send to the API Endpoint and the Token is stored on the client device.
- [x] The token expires.
- [x] If the login data is not correct, an error is promoted and the user has the change to try again.
- [x] If no Token is available, the user is redirected to the login page.

**Comment by code-inflation** [comment]
- [ ] Handle failed API calls when the token is expired or invalid
