### ISSUE TITLE
Workspace Sidebar

### ISSUE THREAD

**Issue by disperate** [grafit-io/grafit#17]
**Description of problem**
As a user it is possible to be part of multiple work-spaces.
A workspace is a logical unit grouping users to a set of documents.

**Solution**
There is a sidebar with all workspaces of the current user. By clicking on a workspace it will become the current workspace. All `article lists` etc. are updated.

**Additional context**
![image](https://user-images.githubusercontent.com/9363716/48319335-f1787700-e60c-11e8-8ae4-d44835fb1408.png)

**Criteria for acceptance**
- [x] a list with all workspaces of the current user is displayed
- [x] by clicking on a workspace, the workspace article list is shown
- [x] the workspace list is hidden on small devices  

The workspace list is only displayed if:
  - [x] a user is authenticated
  - [x] the user is part of more than one workspace
