### ISSUE TITLE
default workspace with tutorial

### ISSUE THREAD

**Issue by disperate** [grafit-io/grafit#19]
**Description of problem**
A new user is not part of any workspace. This leads to a confusing user experience. To prevent a user from having no workspace, it would be an improvement if the user is automatically part of some kind of default workspace after sign up.

**Solution**
The user gets assigned a tutorial workspace. In this workspace are articles with tutorials how to use grafit and explaining the different concepts. There is a new Workspace for every user.

**Criteria for acceptance**
- [ ] After sign up, a user is automatically part of an workspace.
- [ ] The workspace contains articles explaining `Workspace`, `Auto Tagging` and `Node editing`.
- [ ] The user is alone in this workspace.
