### ISSUE TITLE
create workspace

### ISSUE THREAD

**Issue by disperate** [grafit-io/grafit#20]
**Description of problem**
Currently there is no possibility for a user to create a new workspace.

**Solution**
Add a `+` Button to the workspace bar. By clicking a form is opened. The form contains a field for the name and a field for the Initials. After creation the user is added to this workspace. 

After adding the name in the form, a initial suggestion is automatically calculated for the user.
If a single word is added in the name input field, the initials are the first two letters.
If multiple words are added in the name input field, the primary of the first two words are combined.
As soon as the user writes to the Initials field, no further initials suggestions are calculated to prevent from overwriting user content.

Currently the workspace bar is hidden if the user is not part of any workspace. As the create button is part of this bar, it needs to be visible all the time.

**Additional context**
Create Workspace Button:
![new workspace](https://user-images.githubusercontent.com/9363716/48700720-05b00b80-ebed-11e8-861f-8a1c7478cd92.png)

Create Workspace Form
![create workspace](https://user-images.githubusercontent.com/9363716/48700724-0779cf00-ebed-11e8-8ecc-f6ce29f32efa.png)

**Criteria for acceptance**
- [x] A create button is in the workspace bar
- [x] The user can create a workspace by defining a name and initials
- [x] The name and the initials are validated directly in the form
- [x] As long as the user did not manually edit the initials field, the initials are calculated automatically
- [x] The creator is a member of the created workspace
- [x] The workspace bar is never hidden if a user is logged in

**Comment by code-inflation** [comment]
The workspace bar currently fails to reload after a new workspace is created.
