### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by disperate** [grafit-io/grafit#21]
**Description of problem**
Currently there is no possibility to search content. The user has to look through all the articles by hand.

**Solution**

**> Search bar**
There needs to be a search bar:

![searchbar](https://user-images.githubusercontent.com/9363716/48724952-fb146700-ec2a-11e8-805e-0517bc45f1f7.png)

The search bar is shown in every workspace as an overlay:

![searchbar copy](https://user-images.githubusercontent.com/9363716/48724983-0ff0fa80-ec2b-11e8-8d90-ad79ae78cfe6.png)

The overlay is triggered if the user interacts with the search bar.
The search bar can be selected by pressing the keys `Ctrl+F`. [Tutorial for potential solution](https://www.hongkiat.com/blog/keyboard-shortcuts-website/)
To deselect the search bar the user has to click beside the bar or search results.

The search query is persisted in the search bar.

**> Search Results**
The search results are nodes of the knowledge network.
If the user presses enter or clicks on the search icon, a list of all results is displayed.
Minimal length of the search query is >= 1.

The search results contain:
- Nodes where the title fuzzy-matches the search query.
- Nodes matching a full text search. Every word of the search query is matched on its own. Fuzzy if possible.
- Nodes adjunct to title results.

If the user clicks on result, the node is loaded.
The results are displayed as follow:
- If the node contains text, the first fifty characters are displayed.
- If the node contains no text, five adjunct concepts are displayed as badges.

Results are selectable by arrows key and enter.

**> Autoload Results**
The search results are loaded while the user is typing if the following conditions are met:
- The search query is at least three characters long. 
- The last keystroke is older than X milliseconds. [Preventing from loading results for each keystroke.](https://schier.co/blog/2014/12/08/wait-for-user-to-stop-typing-using-javascript.html)

**> Technical stuff**
Doing fuzzy stuff with Neo4j doesn't seem to be super easy.
It's probably easier to build a basic search index in the Postgres database.
[How to build a fuzzy, weighted search index with postgress](http://rachbelaid.com/postgres-full-text-search-is-good-enough/)

**Criteria for acceptance**
- [x] A search bar is displayed on the top of the page
- [x] Search results are returned according to the defined criteria
- [x] Only search results from the current workspace are returned
- [x] Results are shown while typing if the defined conditions are met
- [x] Results are selectable
- [x] Minor misspellings are accepted
