### ISSUE TITLE
document surfing

### ISSUE THREAD

**Issue by disperate** [grafit-io/grafit#22]
**Description of problem**
If the user looks at a node, adjunct nodes are displayed as batches.
To see the adjunct nodes of these nodes, the user has to open them.
Many screen changes can be confusing and the discovery possibilities are limited.

**Solution**
The nodes can be traversed by expanding a in a tree view.

**Additional context**

![dropdown](https://user-images.githubusercontent.com/9363716/48728515-71b66200-ec35-11e8-8a23-b0576cc6f2b3.png)

**Criteria for acceptance**

- [x] Adjunct nodes are displayed as a list
- [x] Nodes can be expanded
- [x] Max depth is five
- [x] Add link to corresponding node

**Comment by disperate** [comment]
Cyclic dependencies are a problem and will be handled with Issue #31.
