### ISSUE TITLE
import existing text files via file uploader

### ISSUE THREAD

**Issue by code-inflation** [grafit-io/grafit#3]
**Description of problem**
A user wants to extract knowledge from existing text sources and import them into the application.

**Solution**
The user should be able to upload existing text files. The text will then be extracted and stored into the datastore. The newly created concept nodes should be linked to the related concepts.

**Additional context**
Which file formats should be supported?
Candidates are: txt, md, docx, pdf, html
Should formatting be included in the analysis? e.g. what is the title of the document.

**Criteria for acceptance**
- [ ] The user can select one or multiple files to upload
- [ ] The text is extracted from the files and saved to the datastore
- [ ] Concepts are extracted and linked to the imported content nodes
