### ISSUE TITLE
Handle N-Grams in Concept Extraction

### ISSUE THREAD

**Issue by code-inflation** [grafit-io/grafit#32]
**Description of problem**
Currently the concept extraction algorithm does not take into regard n-grams. It should be possible for the concept extractor to find n-grams.

**Solution**
The keyphrase extraction algorithm has to be extended to be able to find n-grams. This is done by first tokenizing the text into sentences and then words. n-Grams are then generated from each sentence. Part of Speech Tagging is then used to tag each n-Gram (https://textblob.readthedocs.io/en/dev/quickstart.html#part-of-speech-tagging). The n-Grams are then filtered with the following three rules:
- Each n-Gram has to contain a noun or foreign word
- Each n-Gram has to start with a noun, foreign word or adjective
- Each n-Gram has to end with a noun, foreign word or adjective

After the filter process, the same TF-IDF algorithm as before should be used to determine the best keyphrases.

**Criteria for acceptance**
- [x] The text ist tokenized into sentences and words
- [x] N-Grams are generated on a per sentence basis with a n of 1,2 and 3
- [x] Each word in each n-Gram is PoS-Tagged
- [x] The n-Grams are filtered using the three rules above
- [x] The n-Grams are then fed into the TF-IDF algorithm
