### ISSUE TITLE
Naming and Grouping of Node Connections

### ISSUE THREAD

**Issue by code-inflation** [grafit-io/grafit#38]
**Description of problem**
A user wants to be able to add labels to the connections between different nodes in the knowledge network. The tree visualisation in the article detail view should then group the connections by label name.

**Solution**
The user can set a label when a new connection is created. To label an already existing connection the user can click on the corresponding tag. The user is then prompted to input a new label name.

**Criteria for acceptance**
- [x] The user is prompted to input a label name when creating a new connection
- [x] The user can leave the prompt empty, the connection is then left unlabeled
- [x] When clicking on an existing tag the label can be edited
- [x] The RelatedTree visualisation component groups the connections by label. Connections that have no label are grouped under "unlabeled"
- [x] Automatically generated connections have the "unlabeled" status but that label can be edited the same as with all other labels
- [x] The labels are stored on the connection between the articles in the graph database
