### ISSUE TITLE
Allow adding of Web based sources into the knowledge network

### ISSUE THREAD

**Issue by code-inflation** [grafit-io/grafit#39]
**Description of problem**
A user wants to add data from external (web) sources into the knowledge network. 

**Solution**
A external source is added by copying a URL into the text or title of a node.
On saving, these urls are extracted with a regular expression.
Each of the urls are crawled and the result is cleaned up.

- [X] What file types should be allowed? (html, pdf, docx, etc.)

The resulting content, text only, will be persisted alongside the other node content.  
This external content is added to the search index with the weight C and used in the concept extraction as well.

What are the security concerns? Localhost crawling?

**Criteria for acceptance**
- [x] Define the supported file types
- [x] Define overall crawl timeout. Max 5 seconds
- [x] Extract URLs from post
- [x] Crawl URLs
- [x] Strip HTTP Response Content
- [x] Save web_content
- [x] Add web_content to search index with the weight C
- [ ] Add web_content to graph extraction

**Comment by disperate** [comment]
Currently only sources with the MIME-Type text/html are supported.

**Comment by disperate** [comment]
The web content is not used for the graph extraction because it was not possible to lower the weight of the web_content.  
Because the web_content is often quite long and has a few specific terms they had the overhand and the results got worse.
