### ISSUE TITLE
find content-node via related concepts

### ISSUE THREAD

**Issue by code-inflation** [grafit-io/grafit#6]
**Description of problem**
The user wants to search for content-nodes that are related to one or more specific concepts.

**Solution**
A user can enter one or more concepts into a search bar. The top related nodes should be visualized in a graph (see picture below).
![home](https://user-images.githubusercontent.com/1553087/46953986-a14ed900-d08f-11e8-8b26-b6a5d68df2d6.png)
A list of all related documents is shown as well.
The user can click on a content node to switch to a detail view and read the content of that node.

**Additional context**
- [ ] What graph visualisation library should be used?
- [ ] How are the top related content-nodes calculated?

**Criteria for acceptance**
- [ ] There is a search bar that lets you enter (and delete already entered) concepts
- [ ] All content-nodes that are connected to the selected concept*s are shown in a list
- [ ] The top related content-nodes are displayed in a graph
