### ISSUE TITLE
setup front-end and add article and concept views

### ISSUE THREAD

**Issue by code-inflation** [grafit-io/grafit#7]
**Description of problem**
A user wants to be able to see all articles and the generated concepts. 

**Solution**
The front-end development has to be setup. A front-end framework has to be chosen. A basic front-end development workflow has to be documented.

Add a view with a list containing all concepts and articles. Every item is a link to a detail view.

![image](https://user-images.githubusercontent.com/9363716/47152305-9e94f380-d2dc-11e8-99d2-928d91a498b5.png)

Add a detail view for each node displaying the node content and a link to all adjunct nodes.
A concept node would look like this (has no content):

![detail - concept](https://user-images.githubusercontent.com/9363716/47152351-be2c1c00-d2dc-11e8-97dd-6a293f896fc2.png)

A article node like this:

![detail - article](https://user-images.githubusercontent.com/9363716/47152385-d69c3680-d2dc-11e8-9f9c-096666456be9.png)

**Discussion**
- [x] Evaluate what front-end framework to use

**Criteria for acceptance**
- [x] The front-end is able to display a list of all articles and concepts
- [x] The front-end can display an article and a concept with all adjunct nodes.
- [x] The data is fetched from the REST-API
- [x] The build process of the front-end is integrated into the CI/ CD pipeline
- [x] There are instructions on how to get started developing the front-end
