### ISSUE TITLE
setup back-end and basic graph api

### ISSUE THREAD

**Issue by code-inflation** [grafit-io/grafit#8]
**Description of problem**
There needs to be a back-end that lets you fetch a graph.

**Solution**
The back-end development has to be setup. The language and framework for the development of the back-end have to be evaluated.

**Discussion**
- [x] What language/ framework should be used for back-end development

**Criteria for acceptance**
- [x] There is a REST-endpoint that lets you fetch a graph
- [x] The build process of the back-end is integrated into the CI/ CD pipeline
- [x] There are instructions on how to get started developing the back-end
